autoflowx_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: global-sign-431120-i5
      dataset: autoflowx_staging
      location: europe-west2
      threads: 4
      timeout_seconds: 60
      priority: interactive
      retries: 1
      impersonate_service_account: tfgitworkflow@global-sign-431120-i5.iam.gserviceaccount.com 

    landing:
      type: bigquery
      method: oauth
      project: global-sign-431120-i5
      dataset: autoflowx_landing
      location: europe-west2
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
      impersonate_service_account: tfgitworkflow@global-sign-431120-i5.iam.gserviceaccount.com
