name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/global-sign-431120-i5/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'tfgitworkflow@global-sign-431120-i5.iam.gserviceaccount.com'

      - name: Configure gcloud
        run: |
          gcloud config set global-sign-431120-i5
          gcloud config set compute/zone europe-west2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Run dbt
        run: |
          cd autoflowx_dbt
          dbt deps
          dbt build --full-refresh --target dev
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/autoflowx_dbt

      - name: Build Docker image
        run: |
          docker build -t europe-west2-docker.pkg.dev/global-sign-431120-i5/dbt-model:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-west2-docker.pkg.dev/global-sign-431120-i5/dbt-model:latest
