name: dbt Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: "${path.module}/file.json"
          export_default_credentials: true

  #    - name: Decode GCP Service Account Key
   #     run: |
    #      echo ${{ secrets.GOOGLE_BASE64 }} | base64 --decode > /tmp/service_account_key.json
      
#      - name: Create service account key file
#        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > /tmp/service_account_key.json

     # - name: Check service account key file
     #   run: cat /tmp/service_account_key.json
   #   - name: Create service account key file
   #     run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > /tmp/service_account_key.json

      - name: Configure gcloud auth
        run: gcloud auth activate-service-account --key-file="${path.module}/file.json"

      - name: Run dbt
        run: |
          dbt deps
          dbt build --full-refresh --target dev
        env:
          DBT_PROFILES_DIR: ${{ github.workspace }}/

      - name: Build Docker image
        run: |
          docker build -t europe-west2-docker.pkg.dev/global-sign-431120-i5/dbt-model:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push europe-west2-docker.pkg.dev/global-sign-431120-i5/dbt-model:latest
