name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/378969527341/locations/global/workloadIdentityPools/github/providers/global-sign-431120-i5'
          service_account: 'tfgitworkflow@global-sign-431120-i5.iam.gserviceaccount.com'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-bigquery

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v1

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Docker auth"
        run: |
         gcloud auth configure-docker europe-west2-docker.pkg.dev --quiet

      - name: Build image
        run: |
          pwd
          docker build . --file Dockerfile --tag europe-west2-docker.pkg.dev/global-sign-431120-i5/dbt/image:latest --build-arg PKG=autoflowx_dbt
        working-directory: ${{ github.workspace }}/autoflowx_dbt

      - name: Push image
        run: |
         docker push europe-west2-docker.pkg.dev/global-sign-431120-i5/dbt/image:latest
      
